const $=s=>document.querySelector(s);const tracksEl=$('#tracks');
let tracks=[],playing=false,loopOn=false,projectName='Proyecto verde';let dbPromise;
const DB='BearSiGPTudioDB',STORE='projects',KEY='current';
const db=()=>dbPromise||(dbPromise=new Promise((res,rej)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)}));
const fmt=s=>{s=Math.max(0,s||0);return String(Math.floor(s/60)).padStart(2,'0')+':'+String(Math.floor(s%60)).padStart(2,'0')};
const esc=s=>s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const panText=p=>p<-.02?'L '+Math.round(-p*100):p>.02?'R '+Math.round(p*100):'C';
function makeTrack(file,saved={}){const a=new Audio();a.preload='auto';a.src=URL.createObjectURL(file);const t={id:crypto.randomUUID(),file,a,vol:saved.vol??.85,pan:saved.pan??0,mute:saved.mute??false,solo:saved.solo??false,dur:0};a.onloadedmetadata=()=>{t.dur=a.duration||0;updateDuration();renderTimeline()};return t}
function render(){tracksEl.innerHTML='';if(!tracks.length){tracksEl.innerHTML='<div class="empty">Añade audios para crear tu sesión.<br><small>16.2 guarda los archivos dentro del proyecto.</small></div>';$('#trackCount').textContent='0 pistas';return}tracks.forEach((t,i)=>{const d=document.createElement('div');d.className='track';d.innerHTML=`<div class="trackname"><b title="${esc(t.file.name)}">${esc(t.file.name)}</b><small>Pista ${i+1} · ${fmt(t.dur)}</small></div><div class="volWrap"><div class="mini">VOL <span>${Math.round(t.vol*100)}%</span></div><input class="vol" type="range" min="0" max="1" step=".01" value="${t.vol}"></div><div class="panWrap"><div class="mini">PAN <span>${panText(t.pan)}</span></div><input class="pan" type="range" min="-1" max="1" step=".01" value="${t.pan}"></div><button class="mute ${t.mute?'active':''}">M</button><button class="solo ${t.solo?'active':''}">S</button><button class="del">×</button>`;
 d.querySelector('.vol').oninput=e=>{t.vol=+e.target.value;d.querySelector('.vol span').textContent=Math.round(t.vol*100)+'%';applyMix()};
 d.querySelector('.pan').oninput=e=>{t.pan=+e.target.value;d.querySelector('.pan span').textContent=panText(t.pan);applyMix()};
 d.querySelector('.mute').onclick=()=>{t.mute=!t.mute;d.querySelector('.mute').classList.toggle('active',t.mute);applyMix()};
 d.querySelector('.solo').onclick=()=>{t.solo=!t.solo;d.querySelector('.solo').classList.toggle('active',t.solo);applyMix()};
 d.querySelector('.del').onclick=()=>{t.a.pause();URL.revokeObjectURL(t.a.src);tracks=tracks.filter(x=>x!==t);render();updateDuration();saveProject(true)};tracksEl.appendChild(d)});$('#trackCount').textContent=`${tracks.length} pista${tracks.length>1?'s':''}`;
applyMix();renderTimeline()}
function applyMix(){const solo=tracks.some(t=>t.solo),master=+$('#master').value;tracks.forEach(t=>{t.a.volume=(t.mute||solo&&!t.solo)?0:Math.max(0,Math.min(1,t.vol*master));t.a.style.display='block';try{t.a.preservesPitch=true;t.a.playbackRate=1} catch{}})}
function updateDuration(){const d=Math.max(0,...tracks.map(t=>t.dur||0));$('#duration').textContent=fmt(d)}
function currentSec(){return tracks.length?Math.max(0,...tracks.map(t=>t.a.currentTime||0)):0}
function setPosition(sec){const d=Math.max(0,...tracks.map(t=>t.dur||0));const p=d?Math.max(0,Math.min(1,sec/d)):0;tracks.forEach(t=>{try{t.a.currentTime=Math.min(sec,t.dur||sec)}catch{}});$('#current').dataset.sec=String(sec);$('#current').textContent=fmt(sec);$('#playhead').style.left=(p*100)+'%'}
async function play(){if(!tracks.length)return;for(const t of tracks){try{await t.a.play()}catch{}}playing=true;$('#play').textContent='❚❚';$('#status').textContent='Reproduciendo '+tracks.length+' pistas simultáneamente.'}
function pause(){tracks.forEach(t=>t.a.pause());playing=false;$('#play').textContent='▶';$('#status').textContent='Pausa.'}
function stop(){tracks.forEach(t=>{t.a.pause();try{t.a.currentTime=0}catch{}});playing=false;$('#play').textContent='▶';setPosition(0);$('#status').textContent='Detenido.'}
function tick(){const s=currentSec(),d=Math.max(0,...tracks.map(t=>t.dur||0));if(playing){$('#current').textContent=fmt(s);$('#current').dataset.sec=s;$('#playhead').style.left=(d?s/d*100:0)+'%';if(d&&s>=d-.08){if(loopOn)setPosition(0);else stop()}}requestAnimationFrame(tick)}requestAnimationFrame(tick);
function renderTimeline(){const d=Math.max(0,...tracks.map(t=>t.dur||0));const marks=[];for(let i=0;i<=Math.ceil(d/10);i++)marks.push(fmt(i*10));$('#ruler').textContent=marks.length?marks.join('   '):'0:00';}
$('.timeline').addEventListener('pointerdown',e=>{if(!tracks.length)return;const r=e.currentTarget.getBoundingClientRect(),p=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),d=Math.max(...tracks.map(t=>t.dur||0));setPosition(d*p)});
$('#addBtn').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=e=>{[...e.target.files].filter(f=>f.type.startsWith('audio/')).forEach(f=>tracks.push(makeTrack(f)));e.target.value='';render();$('#status').textContent='Audio cargado. Guarda el proyecto para conservarlo.'};
$('#play').onclick=()=>playing?pause():play();$('#stop').onclick=stop;$('#rewind').onclick=()=>setPosition(Math.max(0,currentSec()-5));$('#master').oninput=()=>{applyMix();$('#masterValue').textContent=Math.round(+$('#master').value*100)+'%'};
$('#loop').onclick=()=>{loopOn=!loopOn;$('#loop').classList.toggle('active',loopOn);$('#status').textContent=loopOn?'Loop activado.':'Loop desactivado.'};
$('#themeBtn').onclick=()=>document.body.classList.toggle('light');$('#newBtn').onclick=async()=>{stop();tracks.forEach(t=>URL.revokeObjectURL(t.a.src));tracks=[];render();try{const d=await db();d.transaction(STORE,'readwrite').objectStore(STORE).delete(KEY)}catch{}$('#status').textContent='Proyecto nuevo.'};
async function saveProject(silent=false){try{const items=[];for(const t of tracks){const buf=await fetch(t.a.src).then(r=>r.blob());items.push({name:t.file.name,type:t.file.type||'audio/*',blob:buf,vol:t.vol,pan:t.pan,mute:t.mute,solo:t.solo})}const data={name:projectName,bpm:+$('#bpm').value,master:+$('#master').value,loop:loopOn,tracks:items,savedAt:Date.now()};const d=await db();await new Promise((res,rej)=>{const r=d.transaction(STORE,'readwrite').objectStore(STORE).put(data,KEY);r.onsuccess=res;r.onerror=()=>rej(r.error)});if(!silent)$('#status').textContent='Proyecto guardado con '+items.length+' audio(s).';}catch(e){if(!silent)$('#status').textContent='No se pudo guardar: '+e.message}}
async function loadProject(){try{const d=await db();const data=await new Promise((res,rej)=>{const r=d.transaction(STORE).objectStore(STORE).get(KEY);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});if(!data){$('#status').textContent='No hay proyecto guardado.';return}stop();tracks.forEach(t=>URL.revokeObjectURL(t.a.src));tracks=[];$('#bpm').value=data.bpm||120;$('#master').value=data.master??.9;loopOn=!!data.loop;$('#loop').classList.toggle('active',loopOn);for(const x of data.tracks||[]){const file=new File([x.blob],x.name,{type:x.type});tracks.push(makeTrack(file,x))}render();$('#status').textContent='Proyecto recuperado: los audios fueron restaurados desde el almacenamiento local.'}catch(e){$('#status').textContent='No se pudo cargar: '+e.message}}
$('#saveBtn').onclick=()=>saveProject(false);$('#loadBtn').onclick=()=>loadProject();$('#bpm').onchange=()=>saveProject(true);$('#masterValue').textContent='90%';updateDuration();renderTimeline();